class ConstClass
	TOWER_SEPARATOR = ';'
	TOWER_CIRCLE_SEPARATOR = '-'
	CIRCLES_CONTENT_SEPARATOR = ':'
	CIRCLES_SEPARATOR = '|'
	DEFAULT_PARSED_CIRCLE = '0:0:0'
	MOVE_COUNT_SEPARATOR ='@'
	MOVE_SEPARATOR ='!'
end
